# Generated by Django 6.0.7 on 2026-07-27 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('owner_id', models.IntegerField(help_text='Session-basierte Owner-ID (ohne User-Account)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=10)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='world_covers/')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorldElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('creature', 'Creature'), ('people', 'People/Volk'), ('map', 'Map'), ('lore', 'Lore Entry')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='world_elements/')),
                ('map_type', models.CharField(blank=True, choices=[('land', 'Land Map'), ('city', 'City Map')], max_length=10)),
                ('habitat', models.CharField(blank=True, max_length=200)),
                ('culture', models.TextField(blank=True)),
                ('language_name', models.CharField(blank=True, max_length=100)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('markers', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_edited_by_id', models.IntegerField(blank=True, help_text='Session-basierte ID', null=True)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='worlds.world')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['world', 'element_type'], name='worlds_worl_world_i_aa5888_idx')],
            },
        ),
    ]
