# Generated by Django 6.0.7 on 2026-07-27 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NixonConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Session-based identifier', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('world', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nixon_conversations', to='worlds.world')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NixonMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('nixon', 'Nixon')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='nixon.nixonconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
