# Generated by Django 6.0.7 on 2026-07-27 19:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('role', models.CharField(choices=[('editor', 'Editor'), ('viewer', 'Viewer')], default='editor', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_by', models.CharField(blank=True, help_text='Optional identifier for who used this code', max_length=50)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='worlds.world')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
