# Generated by Django 6.0.7 on 2026-07-27 19:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldAccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.CharField(blank=True, help_text="Optional: Beschreibung wofür dieser Code ist (z.B. 'Für Spielergruppe A')", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_codes', to='worlds.world')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorldComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, default='Anonym', help_text='Dein Name (optional)', max_length=50)),
                ('content', models.TextField(help_text='Dein Kommentar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Muss vom Welt-Ersteller genehmigt werden')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='worlds.world')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
